### ISSUE TITLE
License

### ISSUE THREAD

**Issue by endian-albin** [javl/image2cpp#34]
Could you please add a license for this tool?

**Comment by javl** [comment]
Could you explain what you would like to do with the tool that would require a license?

**Comment by endian-albin** [comment]
I'd like to be able to redistribute it along with the sources in a git repository. Without redistributing the tool, I can only distribute the source images and the object files but it's not apparent that the latter are the result of the former, and how exactly. Without any license, it's also not clear what I'm allowed to do with it. Copyright law is designed so as to forbid almost everything by default. This is why we need software licenses that explicitly grant rights for things that are under copyright.

**Comment by gromain** [comment]
Hi,

It is good practice to license an open source project, so that others don't have to ask. Since you answered previously to #30 with:
> You can use it in any way you like, though I'd appreciate it if you can link to the original repo. Good luck!

I would recommend choosing the GPL v3 license. This license comes with the obligation for the licensee to disclose the source and put a copyright notice.

Adding a license to this repository is very simple. [Github wrote a guide on how to do that](https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository).
