### ISSUE TITLE
Not an issue: operator/user error - need help, please!

### ISSUE THREAD

**Issue by baqwas** [javl/image2cpp#41]
Hello!

I cannot get the attached image displayed on an OLED 128x96 16-level grayscale display. All my parametric exercises have failed.

Not looking for any accurate mapping (since original is in color and I need grayscale right now but monochrome will suffice for learning curve purposes).

Any advice? Thanks.

Kind regards.

![IoTlogoOled](https://user-images.githubusercontent.com/7071255/105398321-d68bef00-5be7-11eb-84b9-c1f2cebecf3d.png)

**Comment by javl** [comment]
Sorry, I'm no completely sure what your problem is, especially without seeing any code. But as I don't have a similar display, I'm afraid I can't really help.

Maybe Stackoverflow would be a better place for such a question, seeing as I don't think this is image2cpp related but more of a general hardware/software question?
